config/routes.rb
Rails.application.routes.draw do
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  namespace :admin do
    root "branches#index"
    resources :branches, only: :index
    resources :categories, only: :index
    resources :products, only: :index
    resources :employees, only: :index
    resources :customers, only: :index
    resources :synchronization_logs, only: :index
    resources :orders, only: [:index, :show]
  end

   resources :branches, only: :show do
    resources :branch_products, only: :index
    resources :employees, only: :index
    resources :customers, only: :index
    resources :synchronization_logs, only: :index
    resources :orders, only: [:index, :show]
  end

  namespace :api do
    resources :auths, only: :create
    resources :sync_branches, only: [:create, :destroy]
  end
  get "/*page", to: "static_pages#show"
  root "static_pages#show", page: "home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  has_many :customers
  has_many :orders
  has_many :employees
  has_many :branch_products
  has_many :synchronization_logs
  belongs_to :user

  validates :name, :address, presence: true, length: {maximum: 100}
end

app/models/branch_product.rb
class BranchProduct < ApplicationRecord
  belongs_to :branch
  belongs_to :product

  delegate :price, to: :product, prefix: true
  delegate :name, :category_name, :description_truncate, :price, to: :product, prefix: false
end

app/models/category.rb
class Category < ApplicationRecord
  include DescriptionTruncate

  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  VALID_UUID_REGEX = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  self.primary_key = :id

  belongs_to :branch
  has_many :orders

  enum gender: [:male, :female]
  enum level: [:standard, :silver, :gold]

  delegate :name, to: :branch, prefix: true

  validates :email, allow_nil: true, format: {with: VALID_EMAIL_REGEX}
  validates :name, presence: true, length: {maximum: 100}
  validates :id, format: {with: VALID_UUID_REGEX}
end

app/models/employee.rb
class Employee < ApplicationRecord
  VALID_UUID_REGEX = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  self.primary_key = :id

  belongs_to :branch
  has_many :orders

  enum role: [:staff, :manager]
  enum gender: [:male, :female]

  delegate :name, to: :branch, prefix: true

  validates :name, presence: true, length: {maximum: 100}
  validates :email, allow_nil: true, format: {with: VALID_EMAIL_REGEX}
  validates :id, format: {with: VALID_UUID_REGEX}
end

app/models/order.rb
class Order < ApplicationRecord
  VALID_UUID_REGEX = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/

  self.primary_key = :id

  belongs_to :branch
  belongs_to :employee
  belongs_to :customer
  has_many :order_details

  scope :recent_created, ->{order created_at: :desc}

  delegate :name, to: :branch, prefix: true, allow_nil: true
  delegate :name, to: :customer, prefix: true, allow_nil: true
  delegate :name, to: :employee, prefix: true, allow_nil: true

  validates :id, format: {with: VALID_UUID_REGEX}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  VALID_UUID_REGEX = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/

  self.primary_key = :id

  belongs_to :order
  belongs_to :product

  delegate :name, to: :product, prefix: true, allow_nil: true

  validates :id, format: {with: VALID_UUID_REGEX}
end

app/models/product.rb
class Product < ApplicationRecord
  include DescriptionTruncate

  belongs_to :category
  has_many :order_details
  has_many :branch_products

  scope :with_total_quantity, -> do
    joins(:branch_products)
    .select("product_id as id, name, category_id, description, price, sum(quantity) as quantity")
    .group(:product_id)
  end

  delegate :name, to: :category, prefix: true, allow_nil: true
end

app/models/synchronization_log.rb
class SynchronizationLog < ApplicationRecord
  belongs_to :branch

  enum status: [:failed, :success]

  scope :recent_created, ->{order created_at: :desc}

  delegate :name, to: :branch, prefix: true, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_token

  has_one :branch

  enum role: [:admin, :branch]

  delegate :id, to: :branch, prefix: true, allow_nil: true

  def invalidate_token
    update_columns token: nil
  end

  class << self
    def valid_login? email, password
      find_by(email: email.try(:downcase)).try :authenticate, password
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  def authenticate_user!
    unless user_logged_in?
      flash[:warning] = "You need to log in first"
      redirect_to login_path
    end
  end
end

app/controllers/branches_controller.rb
class BranchesController < BranchDetailsController
  def show
    @branch = branch
  end
end

app/controllers/customers_controller.rb
class CustomersController < BranchDetailsController
  def index
    @customers = branch.customers
  end
end

app/controllers/employees_controller.rb
class EmployeesController < BranchDetailsController
  def index
    @employees = branch.employees
  end
end

app/controllers/orders_controller.rb
class OrdersController < BranchDetailsController
  def index
    @orders = branch.orders.recent_created.includes(:customer, :employee)
      .page(params[:page]).per 20
  end

  def show
    @order = branch.orders.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_logged_in, only: [:new, :create]
  def new
  end

  def create
    session_params = params.require :session
    if user = User.valid_login?(session_params[:email], session_params[:password])
      log_in user
      flash[:success] = "Login successful"
      redirect_after_logged_in
    else
      flash.now[:danger] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    authenticate_user!
    log_out
    flash[:warning] = "Logged out!"
    redirect_to root_path
  end

  private
  def check_logged_in
    if user_logged_in?
      flash[:warning] = "Logged in!"
      redirect_to root_path
    end
  end

  def redirect_after_logged_in
    if current_user.admin?
      redirect_to admin_root_path
    else
      redirect_to current_user.branch
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    if valid_page?
      render template: "static_pages/#{params[:page]}"
    else
      raise ActionController::RoutingError.new "Not found"
    end
  end

  private
  def valid_page?
    File.exist? Pathname.new("#{Rails.root}/app/views/static_pages/#{params[:page]}.html.erb")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def index_of counter, page, per_page
    (page - 1) * per_page + counter + 1
  end

  def time_as_format time, format
    l time, format: format
  rescue ArgumentError
    nil
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def user_logged_in?
    current_user.present?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/views/layouts/admin/_sidebar_menu.html.erb
<div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav side-nav">
    <li class="<%= yield :navigation_branches %>">
      <%= link_to "Branches", admin_branches_path %>
    </li>
    <li class="<%= yield :navigation_categories %>">
      <%= link_to "Categories", admin_categories_path %>
    </li>
    <li class="<%= yield :navigation_products %>">
      <%= link_to "Products", admin_products_path %>
    </li>
    <li class="<%= yield :navigation_employees %>">
      <%= link_to "Employees", admin_employees_path %>
    </li>
    <li class="<%= yield :navigation_customers %>">
      <%= link_to "Customers", admin_customers_path %>
    </li>
    <li class="<%= yield :navigation_orders %>">
      <%= link_to "Orders", admin_orders_path %>
    </li>
    <li class="<%= yield :navigation_synchronization_logs %>">
      <%= link_to "Synchronization logs", admin_synchronization_logs_path %>
    </li>
  </ul>
</div>

app/views/layouts/admin/_top_menu.html.erb
<div class="navbar-header">
  <%= link_to "FPT Shop Management", admin_root_path, class: "navbar-brand" %>
</div>
<%= render "layouts/shared/session_menu" %>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FPT Shop Management</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "admin/application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "admin/application", "data-turbolinks-track": "reload" %>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
  </head>

  <body>
    <div>
      <% flash.each do |message_type, message| %>
        <div class="alert text-center alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <div id="wrapper">
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <%= render "layouts/admin/top_menu" %>
        <%= render "layouts/admin/sidebar_menu" %>
      </nav>

      <div id="page-wrapper">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
    <%= link_to "#", {class: "close", "data-dismiss": "alert", "aria-hidden": "true"} do %>
      &times;
    <% end %>
  </div>
<% end %>

app/views/layouts/shared/_session_menu.html.erb
<div class="row session-menu">
  <% if user_logged_in? %>
    <ul class="nav navbar-right top-nav logged_in">
      <li class="dropdown">
        <%= link_to "#", class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
          <%= current_user.email %><b class="caret"></b>
        <% end %>
        <ul class="dropdown-menu">
          <li>
            <% if current_user.admin? %>
              <%= link_to "Admin manager", admin_root_path %>
            <% else %>
              <%= link_to "My page", current_user.branch %>
            <% end %>
          </li>
          <li class="divider"></li>
          <li>
            <%= link_to "Logout", logout_path, method: :delete %>
          </li>
        </ul>
      </li>
    </ul>
  <% else %>
    <div class="navbar-right not-login">
      <%= link_to "Login", login_path %>
    </div>
  <% end %>
</div>

app/views/shared/_order_detail.html.erb
<tr>
  <td><%= order_detail_counter + 1 %></td>
  <td><%= order_detail.product_name %></td>
  <td><%= order_detail.quantity %></td>
  <td><%= order_detail.unit_price %></td>
</tr>

app/views/shared/_show_order_template.html.erb
<h2>Details of order</h2>
<hr/>
<div><b>Id</b>: <%= order.id %></div>
<div><b>Branch name</b>: <%= order.branch_name %></div>
<div><b>Customer name</b>: <%= order.customer_name %></div>
<div><b>Employee name</b>: <%= order.employee_name %></div>
<div><b>Time</b>: <%= time_as_format order.time, :full_datetime %></div>
<div><b>Total price</b>: <%= order.total_price %></div>
<h4>Order details</h4>
<table class="table">
  <thead>
    <tr>
      <th>Index</th>
      <th>Product name</th>
      <th>Quantity</th>
      <th>Unit price</th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: "shared/order_detail", collection: order.order_details, as: :order_detail %>
  </tbody>
</table>