config/routes.rb
Rails.application.routes.draw do
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  namespace :admin do
    root "branches#index"
    resources :branches, only: :index
    resources :categories, only: :index
    resources :products, only: :index
    resources :employees, only: :index
    resources :customers, only: :index
    resources :synchronization_logs, only: :index
    resources :orders, only: [:index, :show]
  end

   resources :branches, only: :show do
    resources :branch_products, only: :index
    resources :employees, only: :index
    resources :customers, only: :index
    resources :synchronization_logs, only: :index
    resources :orders, only: [:index, :show]
  end

  namespace :api do
    resources :auths, only: :create
    resources :sync_branches, only: [:create, :destroy]
  end
  get "/*page", to: "static_pages#show"
  root "static_pages#show", page: "home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/branch.rb
class Branch < ApplicationRecord
  has_many :customers
  has_many :orders
  has_many :employees
  has_many :branch_products
  has_many :synchronization_logs
  belongs_to :user

  validates :name, :address, presence: true, length: {maximum: 100}
end

app/models/branch_product.rb
class BranchProduct < ApplicationRecord
  belongs_to :branch
  belongs_to :product

  delegate :price, to: :product, prefix: true
  delegate :name, :category_name, :description_truncate, :price, to: :product, prefix: false
end

app/models/category.rb
class Category < ApplicationRecord
  include DescriptionTruncate

  has_many :products
end

app/models/customer.rb
class Customer < ApplicationRecord
  VALID_UUID_REGEX = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  self.primary_key = :id

  belongs_to :branch
  has_many :orders

  enum gender: [:male, :female]
  enum level: [:standard, :silver, :gold]

  delegate :name, to: :branch, prefix: true

  validates :email, allow_nil: true, format: {with: VALID_EMAIL_REGEX}
  validates :name, presence: true, length: {maximum: 100}
  validates :id, format: {with: VALID_UUID_REGEX}
end

app/models/employee.rb
class Employee < ApplicationRecord
  VALID_UUID_REGEX = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  self.primary_key = :id

  belongs_to :branch
  has_many :orders

  enum role: [:staff, :manager]
  enum gender: [:male, :female]

  delegate :name, to: :branch, prefix: true

  validates :name, presence: true, length: {maximum: 100}
  validates :email, allow_nil: true, format: {with: VALID_EMAIL_REGEX}
  validates :id, format: {with: VALID_UUID_REGEX}
end

app/models/order.rb
class Order < ApplicationRecord
  VALID_UUID_REGEX = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/

  self.primary_key = :id

  belongs_to :branch
  belongs_to :employee
  belongs_to :customer
  has_many :order_details

  scope :recent_created, ->{order created_at: :desc}

  delegate :name, to: :branch, prefix: true, allow_nil: true
  delegate :name, to: :customer, prefix: true, allow_nil: true
  delegate :name, to: :employee, prefix: true, allow_nil: true

  validates :id, format: {with: VALID_UUID_REGEX}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  VALID_UUID_REGEX = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/

  self.primary_key = :id

  belongs_to :order
  belongs_to :product

  delegate :name, to: :product, prefix: true, allow_nil: true

  validates :id, format: {with: VALID_UUID_REGEX}
end

app/models/product.rb
class Product < ApplicationRecord
  include DescriptionTruncate

  belongs_to :category
  has_many :order_details
  has_many :branch_products

  scope :with_total_quantity, -> do
    joins(:branch_products)
    .select("product_id as id, name, category_id, description, price, sum(quantity) as quantity")
    .group(:product_id)
  end

  delegate :name, to: :category, prefix: true, allow_nil: true
end

app/models/synchronization_log.rb
class SynchronizationLog < ApplicationRecord
  belongs_to :branch

  enum status: [:failed, :success]

  scope :recent_created, ->{order created_at: :desc}

  delegate :name, to: :branch, prefix: true, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_token

  has_one :branch

  enum role: [:admin, :branch]

  delegate :id, to: :branch, prefix: true, allow_nil: true

  def invalidate_token
    update_columns token: nil
  end

  class << self
    def valid_login? email, password
      find_by(email: email.try(:downcase)).try :authenticate, password
    end
  end
end

app/controllers/admin/branches_controller.rb
class Admin::BranchesController < Admin::BaseController
  def index
    @branches = Branch.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  def authenticate_user!
    unless user_logged_in?
      flash[:warning] = "You need to log in first"
      redirect_to login_path
    end
  end
end

app/controllers/branch_details_controller.rb
class BranchDetailsController < ApplicationController
  before_action :authenticate_user!, :authorize_branch

  layout "branch/application"

  def branch
    @branch ||= Branch.find params[:branch_id] || params[:id]
  end

  def authorize_branch
    unless current_user.admin?
      unless branch == current_user.branch
        flash[:danger] = "No permission"
        redirect_to root_path
      end
    end
  end
end

app/controllers/branch_products_controller.rb
class BranchProductsController < BranchDetailsController
  def index
    @products = branch.branch_products.includes product: :category
  end
end

app/controllers/branches_controller.rb
class BranchesController < BranchDetailsController
  def show
    @branch = branch
  end
end

app/controllers/customers_controller.rb
class CustomersController < BranchDetailsController
  def index
    @customers = branch.customers
  end
end

app/controllers/employees_controller.rb
class EmployeesController < BranchDetailsController
  def index
    @employees = branch.employees
  end
end

app/controllers/orders_controller.rb
class OrdersController < BranchDetailsController
  def index
    @orders = branch.orders.recent_created.includes(:customer, :employee)
      .page(params[:page]).per 20
  end

  def show
    @order = branch.orders.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_logged_in, only: [:new, :create]
  def new
  end

  def create
    session_params = params.require :session
    if user = User.valid_login?(session_params[:email], session_params[:password])
      log_in user
      flash[:success] = "Login successful"
      redirect_after_logged_in
    else
      flash.now[:danger] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    authenticate_user!
    log_out
    flash[:warning] = "Logged out!"
    redirect_to root_path
  end

  private
  def check_logged_in
    if user_logged_in?
      flash[:warning] = "Logged in!"
      redirect_to root_path
    end
  end

  def redirect_after_logged_in
    if current_user.admin?
      redirect_to admin_root_path
    else
      redirect_to current_user.branch
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    if valid_page?
      render template: "static_pages/#{params[:page]}"
    else
      raise ActionController::RoutingError.new "Not found"
    end
  end

  private
  def valid_page?
    File.exist? Pathname.new("#{Rails.root}/app/views/static_pages/#{params[:page]}.html.erb")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def index_of counter, page, per_page
    (page - 1) * per_page + counter + 1
  end

  def time_as_format time, format
    l time, format: format
  rescue ArgumentError
    nil
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id] if session[:user_id]
  end

  def user_logged_in?
    current_user.present?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/views/branches/show.html.erb
<% provide :navigation_branches, "active" %>
<h2>All branches</h2>
<hr/>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Working Time</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @branch.id %></td>
      <td><%= @branch.name %></td>
      <td><%= @branch.address %></td>
      <td><%= @branch.phone_number %></td>
      <td><%= @branch.working_time %></td>
    </tr>
  </tbody>
</table>

app/views/layouts/branch/_sidebar_menu.html.erb
<div class="collapse navbar-collapse navbar-ex1-collapse">
  <ul class="nav navbar-nav side-nav">
    <li class="<%= yield :navigation_branches %>">
      <%= link_to "My Branch", branch_path(branch) %>
    </li>
    <li class="<%= yield :navigation_products %>">
      <%= link_to "My Products", branch_branch_products_path(branch) %>
    </li>
    <li class="<%= yield :navigation_employees %>">
      <%= link_to "My Employees", branch_employees_path(branch) %>
    </li>
    <li class="<%= yield :navigation_customers %>">
      <%= link_to "My Customers", branch_customers_path(branch) %>
    </li>
    <li class="<%= yield :navigation_orders %>">
      <%= link_to "My Orders", branch_orders_path(branch) %>
    </li>
    <li class="<%= yield :navigation_synchronization_logs %>">
      <%= link_to "My synchronization logs", branch_synchronization_logs_path(branch) %>
    </li>
  </ul>
</div>

app/views/layouts/branch/_top_menu.html.erb
<div class="navbar-header">
  <%= link_to "FPT Shop Management - Branch: #{branch.name}", branch, class: "navbar-brand" %>
</div>
<%= render "layouts/shared/session_menu" %>

app/views/layouts/branch/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FPT Shop Management | <%= @branch.name %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "branch/application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "branch/application", "data-turbolinks-track": "reload" %>
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.js"></script>
  </head>

  <body>
    <div id="wrapper">
      <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <%= render "layouts/branch/top_menu", branch: @branch %>
        <%= render "layouts/branch/sidebar_menu", branch: @branch %>
      </nav>
      <div id="page-wrapper">
        <div class="container-fluid">
          <%= render "layouts/shared/flash" %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>